import { motion } from "framer-motion";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import AnimatedHeader from "../components/animated-header.component";
import Logo from "../components/chelsea-logo-svg.component";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chelsea FC News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AnimatedHeader text={"CHELSEA FOOTBALL CLUB"} />

        <h1>Check out the fixtures page!</h1>
        <Link href="/fixtures">
          <a>Fixtures</a>
        </Link>
        <Logo dimensions={700} />
      </main>
    </div>
  );
};

export default Home;
